### PR TITLE
Parallel processing support

### PR DESCRIPTION
**Pull request by StoneMoe**
Load all CAB files at once, and finished everything under 3 minutes.
```
16 Core, 64GB RAM, PCIE4 SSD
Before: ~30 mins
After: ~3 mins
```
TLDR;
1. Drop dotNet 4.7.2 support due to poorly concurrent support
2. Add some fine tuned data structures for concurrent data access
3. Replace `for` and `foreach` with `Parallel.For` and `Parallel.ForEach`

### CODE REVIEW

**Comment by StoneMoe** [comment]
I don't write C# too much, looking forward for a code review :)

**Comment by Razmoth** [comment]
Greetings.

Will check it out, thanks for the PR.

**Comment by Razmoth** [comment]
@StoneMoe Parallel seems to break BLK method when loading files.

**Comment by StoneMoe** [comment]
> @StoneMoe Parallel seems to break BLK method when loading files.

Hi, I didn't see any issue while loading `.blk` files, could you give me more details?

**Comment by StoneMoe** [comment]
OK I did see some random crash appears at `sceneTreeView.BeginUpdate(); AssetStudioGUIForm.cs:Line 272`
I'll take a look

**Comment by Razmoth** [comment]
Closing due to future plans to discontinue `CABMap` support (see [here](https://github.com/Razmoth/GenshinStudio/issues/8#issuecomment-1125317831))

**Pull request closed without merging**
